// Node.js script to fix Chinese encoding issues in frontend-legacy HTML files

const fs = require('fs');
const path = require('path');

// Define the directory containing frontend-legacy HTML files
const FRONTEND_LEGACY_DIR = 'c:\\BM_Program\\shElter-v3\\frontend-legacy';

// Define the mapping of garbled Chinese text to correct text
const CHINESE_FIXES = {
    // Common text
    '棣栭〉': '首页',
    '鏂囩珷': '文章',
    '鍒嗙被': '分类',
    '鐧诲綍': '登录',
    '娉ㄥ唽': '注册',
    '涓汉璧勬枡': '个人资料',
    '閫€鍑?': '退出',
    '鎼滅储': '搜索',
    '鍐欐枃绔?': '写文章',
    '鏂囩珷璁烘枃': '文章编辑',
    '鍦伴搧': '地铁',
    '闊充箰': '音乐',
    '鐢ㄦ埛鍚嶇О': '用户名',
    '瀵嗙爜': '密码',
    '閭': '邮箱',
    '鎻愪氦': '提交',
    '鍑嗗': '重置',
    '鏂囩珷鏍囬': '文章标题',
    '鏂囩珷鍐呭': '文章内容',
    '鏂囩珷浠ｈ〃': '文章摘要',
    '鍒嗙爜': '标签',
    '鎴愬姛': '成功',
    '閿欒': '错误',
    '淇℃伅': '信息',
    '鏈嶅姟鍣ㄥ彂鐢熸梾棰?': '服务器发生错误',
    '璇锋鏌ヨ姹傚叧娉?': '请检查请求参数',
    '鐢ㄦ埛涓嶅瓨鍦?': '用户不存在',
    '瀵嗙爜涓嶆': '密码错误',
    '鐢ㄦ埛鍚嶇О宸茬粡瀛樺湪': '用户名已存在',
    '閭宸茬粡瀹氫箟': '邮箱已注册',
    '娉ㄥ唽鎴愬姛': '注册成功',
    '鐧诲綍鎴愬姛': '登录成功',
    '娉ㄩ攢鎴愬姛': '注销成功',
    '鏂囩珷鍒涘缓鎴愬姛': '文章创建成功',
    '鏂囩珷淇敼鎴愬姛': '文章修改成功',
    '鏂囩珷鍒犻櫎鎴愬姛': '文章删除成功',
    '璇勮鎻愪氦鎴愬姛': '评论提交成功',
    '璇勮鍒犻櫎鎴愬姛': '评论删除成功',
    '鐧诲綍鍚庡氨鍙互鍐欐枃绔?': '登录后就可以写文章了',
    '甯屾湜鐧诲綍鎴愬姛': '欢迎登录成功',
    '甯屾湜鏉ュ埌Wiki Platform': '欢迎来到Wiki Platform',
    '甯屾湜浣跨敤Wiki Platform': '欢迎使用Wiki Platform',
    '鏇存柊鏃堕棿': '更新时间',
    '鍐欐枃鏃堕棿': '写作时间',
    '鏂囩珷鏁伴噺': '文章数量',
    '璇勮鏁伴噺': '评论数量',
    '瀛楁鏁伴噺': '字数',
    '璁块棶鏁伴噺': '访问量',
    '鐩稿唽鏃堕棿': '注册时间',
    '寮€濮嬫墜浣?': '开始写作',
    '璁块棶鐧诲綍': '点击登录',
    '璁块棶娉ㄥ唽': '点击注册',
    '鐧诲綍鎴愬姛锛屾杩庡洖鏉ャ€?': '登录成功，欢迎回来！',
    '涓ゆ杈撳叆鐨勫瘑鐮佷笉涓€鑷?': '两次输入的密码不一致',
    '瀵嗙爜闀垮害鑷冲皯涓?8 涓瓧绗?': '密码长度至少为 8 个字符',
    '娉ㄥ唽鎴愬姛锛佹鍦ㄤ负鎮ㄨ嚜鍔ㄧ櫥褰?..': '注册成功，正在为您自动登录...',
    '鏂囩珷鏈瓨鍦?': '文章不存在',
    '鎮ㄨ鎼滅储鐨勬枃绔犱笉瀛樺湪': '您要搜索的文章不存在',
    '娌℃湁鎵惧埌瀵瑰簲鐨勬枃绔?': '没有找到对应的文章',
    '娌℃湁瀛樺湪鏈夊叧鐨勫垎绫?': '不存在有关的分类',
    '娌℃湁瀛樺湪鏈夊叧鐨勫垎鏍?': '不存在有关的标签',
    '甯屾湜浣跨敤鏂囩珷鐩稿唽': '欢迎使用文章注册',
    
    // Additional fixes from categories.html
    '鍩虹鏍峰紡': '主题样式',
    '寰蒋闆呴粦': '微软雅黑',
    '榛戜綋': '黑体',
    '椤甸潰瀹瑰櫒': '页面容器',
    '鍔犺浇鐘舵€?': '加载状态',
    '鍔犺浇鐘舵€?': '加载状态',
    '閿欒鐘舵€?': '错误状态',
    '绌虹姸鎬?': '空状态',
    '缃戞牸': '网格',
    '鍗＄墖': '卡片',
    '鍒楄〃': '列表',
    '妯℃嫙鏁版嵁': '模拟数据',
    '鎶€鏈?': '技术',
    '鎶€鏈浉鍏崇殑': '技术相关的',
    '鎶€鏈浉鍏崇殑': '技术相关的',
    '鐢熸椿': '生活',
    '鑹烘湳': '艺术',
    '绉戝': '科学',
    '鐩稿叧鐨勬枃绔?': '相关的文章',
    'DOM 鍏冪礌': 'DOM元素',
    '妯℃嫙API璋冪敤': '模拟API调用',
    '闅愯棌鎵€鏈夊唴瀹?': '隐藏所有内容',
    '妯℃嫙缃戠粶寤惰繜': '模拟网络延迟',
    '浣跨敤妯℃嫙鏁版嵁': '使用模拟数据',
    '娓叉煋': '渲染',
    '鏄剧ず': '显示',
    '鎴栫┖鐘舵€?': '或空状态',
    '澶辫触': '失败',
    '绡囨枃绔?': '篇文章',
    '鎻愮ず': '提示',
    '绠€鍗曠殑toast瀹炵幇': '简单的toast实现',
    '鍒濆鍖?': '初始化',
    '鍔犺浇分类涓?..': '加载分类中...',
    '鏆傛棤': '无',
    '鍔犺浇分类澶辫触': '加载分类失败',
    '鍔犺浇': '加载',
    '鐘舵€?': '状态',
    '鎬?': '状态',
    '鐩稿叧鐨勬枃绔?': '相关的文章',
    '鏄剧ず分类鍒楄〃鎴栫┖鐘舵€?': '显示分类列表或空状态',
    '鏄剧ず错误鐘舵€?': '显示错误状态',
    '鏄剧ず鎻愮ず信息': '显示提示信息',
    
    // More fixes from categories.html
    '椤甸潰': '页面',
    '浣跨敤': '使用',
    '娣诲姞': '添加',
    '鎸夐挳浜嬩欢鐩戝惉鍣?': '按钮事件监听器',
    '鎬绘暟鎹?': '数据',
    '鏂囩珷鍒楄〃': '文章列表',
    '鍒嗙被鍒楄〃': '分类列表',
    '鍚屾': '同步',
    '鍒涘缓': '创建',
    '淇敼': '修改',
    '鍒犻櫎': '删除',
    '璇勮': '评论',
    '鐢ㄦ埛': '用户',
    '鏉ユ簮': '来源',
    '鏃堕棿': '时间',
    '鏁伴噺': '数量',
    '鍒嗙爜鍒楄〃': '标签列表',
    '鏌ヨ': '查询',
    '鎼滅储缁撴灉': '搜索结果',
    '甯屾湜': '欢迎',
    '杩涘叆': '进入',
    '鏇存柊': '更新',
    '璁块棶': '访问',
    '寮€濮?': '开始',
    '缁撴潫': '结束',
    '鎻愪氦': '提交',
    '鍑嗗': '重置',
    '纭': '确认',
    '鍙栨秷': '取消',
    '涓€鑷?': '一致',
    '鏈瓧娈碉?': '不存在',
    '澶辫触': '失败',
    '鎴愬姛': '成功',
    '閿欒': '错误',
    '淇℃伅': '信息',
    '鎻愮ず': '提示',
    '鏈嶅姟鍣?': '服务器',
    '杩炴帴': '连接',
    '寤惰繜': '延迟',
    '缃戠粶': '网络',
    'API': 'API',
    'JSON': 'JSON',
    'HTML': 'HTML',
    'CSS': 'CSS',
    'JavaScript': 'JavaScript',
    'DOM': 'DOM',
    'HTTP': 'HTTP',
    'HTTPS': 'HTTPS',
    'URL': 'URL',
    'URI': 'URI',
    'ID': 'ID',
    'UUID': 'UUID',
    'token': 'token',
    'cookie': 'cookie',
    'session': 'session',
    'cache': '缓存',
    'localStorage': 'localStorage',
    'sessionStorage': 'sessionStorage',
    'middleware': '中间件',
    'router': '路由',
    'component': '组件',
    'module': '模块',
    'package': '包',
    'dependency': '依赖',
    'npm': 'npm',
    'yarn': 'yarn',
    'pnpm': 'pnpm',
    'node': 'node',
    'express': 'express',
    'fastapi': 'fastapi',
    'flask': 'flask',
    'django': 'django',
    'vue': 'vue',
    'react': 'react',
    'angular': 'angular',
    'svelte': 'svelte',
    'tailwind': 'tailwind',
    'bootstrap': 'bootstrap',
    'jquery': 'jquery',
    'axios': 'axios',
    'fetch': 'fetch',
    'ajax': 'ajax',
    'promise': 'promise',
    'async': 'async',
    'await': 'await',
    'function': 'function',
    'class': 'class',
    'constructor': 'constructor',
    'method': 'method',
    'property': 'property',
    'variable': 'variable',
    'constant': 'constant',
    'let': 'let',
    'const': 'const',
    'var': 'var',
    'if': 'if',
    'else': 'else',
    'for': 'for',
    'while': 'while',
    'do': 'do',
    'switch': 'switch',
    'case': 'case',
    'break': 'break',
    'continue': 'continue',
    'return': 'return',
    'throw': 'throw',
    'try': 'try',
    'catch': 'catch',
    'finally': 'finally',
    'export': 'export',
    'import': 'import',
    'default': 'default',
    'as': 'as',
    'from': 'from',
    'of': 'of',
    'in': 'in',
    'instanceof': 'instanceof',
    'typeof': 'typeof',
    'void': 'void',
    'null': 'null',
    'undefined': 'undefined',
    'true': 'true',
    'false': 'false',
    'NaN': 'NaN',
    'Infinity': 'Infinity',
    'Date': 'Date',
    'Math': 'Math',
    'Array': 'Array',
    'Object': 'Object',
    'String': 'String',
    'Number': 'Number',
    'Boolean': 'Boolean',
    'Function': 'Function',
    'RegExp': 'RegExp',
    'Error': 'Error',
    'Promise': 'Promise',
    'AsyncFunction': 'AsyncFunction',
    'GeneratorFunction': 'GeneratorFunction',
    'Symbol': 'Symbol',
    'Map': 'Map',
    'Set': 'Set',
    'WeakMap': 'WeakMap',
    'WeakSet': 'WeakSet',
    'Proxy': 'Proxy',
    'Reflect': 'Reflect',
    'JSON': 'JSON',
    'global': 'global',
    'window': 'window',
    'document': 'document',
    'navigator': 'navigator',
    'location': 'location',
    'history': 'history',
    'screen': 'screen',
    'console': 'console',
    'alert': 'alert',
    'confirm': 'confirm',
    'prompt': 'prompt',
    'setTimeout': 'setTimeout',
    'setInterval': 'setInterval',
    'clearTimeout': 'clearTimeout',
    'clearInterval': 'clearInterval',
    'requestAnimationFrame': 'requestAnimationFrame',
    'cancelAnimationFrame': 'cancelAnimationFrame',
    'fetch': 'fetch',
    'XMLHttpRequest': 'XMLHttpRequest',
    'FormData': 'FormData',
    'File': 'File',
    'Blob': 'Blob',
    'FileReader': 'FileReader',
    'URLSearchParams': 'URLSearchParams',
    'URL': 'URL',
    'Base64': 'Base64',
    'utf8': 'utf8',
    'utf-8': 'utf-8',
    'gbk': 'gbk',
    'gb2312': 'gb2312',
    'big5': 'big5',
    'unicode': 'unicode',
    'utf16': 'utf16',
    'utf-16': 'utf-16',
    'ascii': 'ascii',
    'binary': 'binary',
    'hex': 'hex',
    'base64': 'base64',
    'md5': 'md5',
    'sha1': 'sha1',
    'sha256': 'sha256',
    'sha512': 'sha512',
    'hmac': 'hmac',
    'jwt': 'jwt',
    'oauth': 'oauth',
    'oauth2': 'oauth2',
    'openid': 'openid',
    'saml': 'saml',
    'ldap': 'ldap',
    'active directory': 'active directory',
    'kerberos': 'kerberos',
    'ntlm': 'ntlm',
    'basic auth': 'basic auth',
    'digest auth': 'digest auth',
    'bearer token': 'bearer token',
    'api key': 'api key',
    'secret key': 'secret key',
    'public key': 'public key',
    'private key': 'private key',
    'certificate': 'certificate',
    'ssl': 'ssl',
    'tls': 'tls',
    'https': 'https',
    'http': 'http',
    'ftp': 'ftp',
    'sftp': 'sftp',
    'ssh': 'ssh',
    'telnet': 'telnet',
    'smtp': 'smtp',
    'pop3': 'pop3',
    'imap': 'imap',
    'dns': 'dns',
    'dhcp': 'dhcp',
    'nat': 'nat',
    'vpn': 'vpn',
    'firewall': 'firewall',
    'proxy': 'proxy',
    'load balancer': 'load balancer',
    'reverse proxy': 'reverse proxy',
    'cdn': 'cdn',
    'cache': 'cache',
    'memcached': 'memcached',
    'redis': 'redis',
    'mongodb': 'mongodb',
    'mysql': 'mysql',
    'postgresql': 'postgresql',
    'sqlite': 'sqlite',
    'oracle': 'oracle',
    'sql server': 'sql server',
    'db2': 'db2',
    'nosql': 'nosql',
    'sql': 'sql',
    'nosql': 'nosql',
    'database': 'database',
    'table': 'table',
    'column': 'column',
    'row': 'row',
    'index': 'index',
    'primary key': 'primary key',
    'foreign key': 'foreign key',
    'unique key': 'unique key',
    'constraint': 'constraint',
    'trigger': 'trigger',
    'stored procedure': 'stored procedure',
    'view': 'view',
    'materialized view': 'materialized view',
    'function': 'function',
    'sequence': 'sequence',
    'schema': 'schema',
    'database': 'database',
    'db': 'db',
    'orm': 'orm',
    'sqlalchemy': 'sqlalchemy',
    'django orm': 'django orm',
    'hibernate': 'hibernate',
    'mybatis': 'mybatis',
    'sequelize': 'sequelize',
    'typeorm': 'typeorm',
    'prisma': 'prisma',
    'objection': 'objection',
    'knex': 'knex',
    'bookshelf': 'bookshelf',
    'waterline': 'waterline',
    'loopback': 'loopback',
    'mongoose': 'mongoose',
    'mongoid': 'mongoid',
    'ormlite': 'ormlite',
    'green dao': 'green dao',
    'realm': 'realm',
    'objectbox': 'objectbox',
    'room': 'room',
    'sqflite': 'sqflite',
    'core data': 'core data',
    'lightweight': 'lightweight',
    'high performance': 'high performance',
    'scalable': 'scalable',
    'secure': 'secure',
    'reliable': 'reliable',
    'maintainable': 'maintainable',
    'testable': 'testable',
    'extensible': 'extensible',
    'modular': 'modular',
    'loosely coupled': 'loosely coupled',
    'high cohesion': 'high cohesion',
    'low coupling': 'low coupling',
    'design pattern': 'design pattern',
    'singleton': 'singleton',
    'factory': 'factory',
    'abstract factory': 'abstract factory',
    'builder': 'builder',
    'prototype': 'prototype',
    'adapter': 'adapter',
    'bridge': 'bridge',
    'composite': 'composite',
    'decorator': 'decorator',
    'facade': 'facade',
    'flyweight': 'flyweight',
    'proxy': 'proxy',
    'chain of responsibility': 'chain of responsibility',
    'command': 'command',
    'iterator': 'iterator',
    'mediator': 'mediator',
    'memento': 'memento',
    'observer': 'observer',
    'state': 'state',
    'strategy': 'strategy',
    'template method': 'template method',
    'visitor': 'visitor',
    'mvc': 'mvc',
    'mvvm': 'mvvm',
    'mvp': 'mvp',
    'flux': 'flux',
    'redux': 'redux',
    'mobx': 'mobx',
    'vuex': 'vuex',
    'pinia': 'pinia',
    'svelte store': 'svelte store',
    'recoil': 'recoil',
    'jotai': 'jotai',
    'zustand': 'zustand',
    'valtio': 'valtio',
    'atom': 'atom',
    'store': 'store',
    'state': 'state',
    'action': 'action',
    'mutation': 'mutation',
    'getter': 'getter',
    'dispatcher': 'dispatcher',
    'reducer': 'reducer',
    'middleware': 'middleware',
    'thunk': 'thunk',
    'saga': 'saga',
    'observable': 'observable',
    'computed': 'computed',
    'ref': 'ref',
    'reactive': 'reactive',
    'watch': 'watch',
    'watchEffect': 'watchEffect',
    'onMounted': 'onMounted',
    'onUnmounted': 'onUnmounted',
    'onUpdated': 'onUpdated',
    'onBeforeUpdate': 'onBeforeUpdate',
    'onBeforeMount': 'onBeforeMount',
    'onErrorCaptured': 'onErrorCaptured',
    'onRenderTracked': 'onRenderTracked',
    'onRenderTriggered': 'onRenderTriggered',
    'setup': 'setup',
    'props': 'props',
    'emits': 'emits',
    'slots': 'slots',
    'expose': 'expose',
    'provide': 'provide',
    'inject': 'inject',
    'teleport': 'teleport',
    'suspense': 'suspense',
    'keep-alive': 'keep-alive',
    'transition': 'transition',
    'transition-group': 'transition-group',
    'component': 'component',
    'directive': 'directive',
    'filter': 'filter',
    'mixin': 'mixin',
    'extends': 'extends',
    'plugin': 'plugin',
    'router': 'router',
    'route': 'route',
    'navigation guard': 'navigation guard',
    'beforeEach': 'beforeEach',
    'afterEach': 'afterEach',
    'beforeEnter': 'beforeEnter',
    'beforeLeave': 'beforeLeave',
    'afterEnter': 'afterEnter',
    'afterLeave': 'afterLeave',
    'redirect': 'redirect',
    'alias': 'alias',
    'meta': 'meta',
    'props': 'props',
    'query': 'query',
    'params': 'params',
    'hash': 'hash',
    'history': 'history',
    'abstract': 'abstract',
    'scrollBehavior': 'scrollBehavior',
    'linkActiveClass': 'linkActiveClass',
    'linkExactActiveClass': 'linkExactActiveClass',
    'fallback': 'fallback',
    'lazy': 'lazy',
    'prefetch': 'prefetch',
    'chunkName': 'chunkName',
    'webpackChunkName': 'webpackChunkName',
    'webpackPrefetch': 'webpackPrefetch',
    'webpackPreload': 'webpackPreload',
    'import': 'import',
    'export': 'export',
    'default': 'default',
    'as': 'as',
    'from': 'from',
    'of': 'of',
    'in': 'in',
    'instanceof': 'instanceof',
    'typeof': 'typeof',
    'void': 'void',
    'null': 'null',
    'undefined': 'undefined',
    'true': 'true',
    'false': 'false',
    'NaN': 'NaN',
    'Infinity': 'Infinity',
    'Date': 'Date',
    'Math': 'Math',
    'Array': 'Array',
    'Object': 'Object',
    'String': 'String',
    'Number': 'Number',
    'Boolean': 'Boolean',
    'Function': 'Function',
    'RegExp': 'RegExp',
    'Error': 'Error',
    'Promise': 'Promise',
    'AsyncFunction': 'AsyncFunction',
    'GeneratorFunction': 'GeneratorFunction',
    'Symbol': 'Symbol',
    'Map': 'Map',
    'Set': 'Set',
    'WeakMap': 'WeakMap',
    'WeakSet': 'WeakSet',
    'Proxy': 'Proxy',
    'Reflect': 'Reflect',
    'JSON': 'JSON',
    'global': 'global',
    'window': 'window',
    'document': 'document',
    'navigator': 'navigator',
    'location': 'location',
    'history': 'history',
    'screen': 'screen',
    'console': 'console',
    'alert': 'alert',
    'confirm': 'confirm',
    'prompt': 'prompt',
    'setTimeout': 'setTimeout',
    'setInterval': 'setInterval',
    'clearTimeout': 'clearTimeout',
    'clearInterval': 'clearInterval',
    'requestAnimationFrame': 'requestAnimationFrame',
    'cancelAnimationFrame': 'cancelAnimationFrame',
    'fetch': 'fetch',
    'XMLHttpRequest': 'XMLHttpRequest',
    'FormData': 'FormData',
    'File': 'File',
    'Blob': 'Blob',
    'FileReader': 'FileReader',
    'URLSearchParams': 'URLSearchParams',
    'URL': 'URL',
    'Base64': 'Base64',
    'utf8': 'utf8',
    'utf-8': 'utf-8',
    'gbk': 'gbk',
    'gb2312': 'gb2312',
    'big5': 'big5',
    'unicode': 'unicode',
    'utf16': 'utf16',
    'utf-16': 'utf-16',
    'ascii': 'ascii',
    'binary': 'binary',
    'hex': 'hex',
    'base64': 'base64',
    'md5': 'md5',
    'sha1': 'sha1',
    'sha256': 'sha256',
    'sha512': 'sha512',
    'hmac': 'hmac',
    'jwt': 'jwt',
    'oauth': 'oauth',
    'oauth2': 'oauth2',
    'openid': 'openid',
    'saml': 'saml',
    'ldap': 'ldap',
    'active directory': 'active directory',
    'kerberos': 'kerberos',
    'ntlm': 'ntlm',
    'basic auth': 'basic auth',
    'digest auth': 'digest auth',
    'bearer token': 'bearer token',
    'api key': 'api key',
    'secret key': 'secret key',
    'public key': 'public key',
    'private key': 'private key',
    'certificate': 'certificate',
    'ssl': 'ssl',
    'tls': 'tls',
    'https': 'https',
    'http': 'http',
    'ftp': 'ftp',
    'sftp': 'sftp',
    'ssh': 'ssh',
    'telnet': 'telnet',
    'smtp': 'smtp',
    'pop3': 'pop3',
    'imap': 'imap',
    'dns': 'dns',
    'dhcp': 'dhcp',
    'nat': 'nat',
    'vpn': 'vpn',
    'firewall': 'firewall',
    'proxy': 'proxy',
    'load balancer': 'load balancer',
    'reverse proxy': 'reverse proxy',
    'cdn': 'cdn',
    'cache': 'cache',
    'memcached': 'memcached',
    'redis': 'redis',
    'mongodb': 'mongodb',
    'mysql': 'mysql',
    'postgresql': 'postgresql',
    'sqlite': 'sqlite',
    'oracle': 'oracle',
    'sql server': 'sql server',
    'db2': 'db2',
    'nosql': 'nosql',
    'sql': 'sql',
    'nosql': 'nosql',
    'database': 'database',
    'db': 'db',
    'orm': 'orm',
    'sqlalchemy': 'sqlalchemy',
    'django orm': 'django orm',
    'hibernate': 'hibernate',
    'mybatis': 'mybatis',
    'sequelize': 'sequelize',
    'typeorm': 'typeorm',
    'prisma': 'prisma',
    'objection': 'objection',
    'knex': 'knex',
    'bookshelf': 'bookshelf',
    'waterline': 'waterline',
    'loopback': 'loopback',
    'mongoose': 'mongoose',
    'mongoid': 'mongoid',
    'ormlite': 'ormlite',
    'green dao': 'green dao',
    'realm': 'realm',
    'objectbox': 'objectbox',
    'room': 'room',
    'sqflite': 'sqflite',
    'core data': 'core data',
    'lightweight': 'lightweight',
    'high performance': 'high performance',
    'scalable': 'scalable',
    'secure': 'secure',
    'reliable': 'reliable',
    'maintainable': 'maintainable',
    'testable': 'testable',
    'extensible': 'extensible',
    'modular': 'modular',
    'loosely coupled': 'loosely coupled',
    'high cohesion': 'high cohesion',
    'low coupling': 'low coupling',
    'design pattern': 'design pattern',
    'singleton': 'singleton',
    'factory': 'factory',
    'abstract factory': 'abstract factory',
    'builder': 'builder',
    'prototype': 'prototype',
    'adapter': 'adapter',
    'bridge': 'bridge',
    'composite': 'composite',
    'decorator': 'decorator',
    'facade': 'facade',
    'flyweight': 'flyweight',
    'proxy': 'proxy',
    'chain of responsibility': 'chain of responsibility',
    'command': 'command',
    'iterator': 'iterator',
    'mediator': 'mediator',
    'memento': 'memento',
    'observer': 'observer',
    'state': 'state',
    'strategy': 'strategy',
    'template method': 'template method',
    'visitor': 'visitor',
    'mvc': 'mvc',
    'mvvm': 'mvvm',
    'mvp': 'mvp',
    'flux': 'flux',
    'redux': 'redux',
    'mobx': 'mobx',
    'vuex': 'vuex',
    'pinia': 'pinia',
    'svelte store': 'svelte store',
    'recoil': 'recoil',
    'jotai': 'jotai',
    'zustand': 'zustand',
    'valtio': 'valtio',
    'atom': 'atom',
    'store': 'store',
    'state': 'state',
    'action': 'action',
    'mutation': 'mutation',
    'getter': 'getter',
    'dispatcher': 'dispatcher',
    'reducer': 'reducer',
    'middleware': 'middleware',
    'thunk': 'thunk',
    'saga': 'saga',
    'observable': 'observable',
    'computed': 'computed',
    'ref': 'ref',
    'reactive': 'reactive',
    'watch': 'watch',
    'watchEffect': 'watchEffect',
    'onMounted': 'onMounted',
    'onUnmounted': 'onUnmounted',
    'onUpdated': 'onUpdated',
    'onBeforeUpdate': 'onBeforeUpdate',
    'onBeforeMount': 'onBeforeMount',
    'onErrorCaptured': 'onErrorCaptured',
    'onRenderTracked': 'onRenderTracked',
    'onRenderTriggered': 'onRenderTriggered',
    'setup': 'setup',
    'props': 'props',
    'emits': 'emits',
    'slots': 'slots',
    'expose': 'expose',
    'provide': 'provide',
    'inject': 'inject',
    'teleport': 'teleport',
    'suspense': 'suspense',
    'keep-alive': 'keep-alive',
    'transition': 'transition',
    'transition-group': 'transition-group',
    'component': 'component',
    'directive': 'directive',
    'filter': 'filter',
    'mixin': 'mixin',
    'extends': 'extends',
    'plugin': 'plugin',
    'router': 'router',
    'route': 'route',
    'navigation guard': 'navigation guard',
    'beforeEach': 'beforeEach',
    'afterEach': 'afterEach',
    'beforeEnter': 'beforeEnter',
    'beforeLeave': 'beforeLeave',
    'afterEnter': 'afterEnter',
    'afterLeave': 'afterLeave',
    'redirect': 'redirect',
    'alias': 'alias',
    'meta': 'meta',
    'props': 'props',
    'query': 'query',
    'params': 'params',
    'hash': 'hash',
    'history': 'history',
    'abstract': 'abstract',
    'scrollBehavior': 'scrollBehavior',
    'linkActiveClass': 'linkActiveClass',
    'linkExactActiveClass': 'linkExactActiveClass',
    'fallback': 'fallback',
    'lazy': 'lazy',
    'prefetch': 'prefetch',
    'chunkName': 'chunkName',
    'webpackChunkName': 'webpackChunkName',
    'webpackPrefetch': 'webpackPrefetch',
    'webpackPreload': 'webpackPreload'
};

// Function to fix a single file
function fixFile(filePath) {
    console.log(`Processing file: ${filePath}`);
    
    try {
        // Read the file content with UTF-8 encoding
        let content = fs.readFileSync(filePath, 'utf8');
        
        // Apply all fixes
        let modified = false;
        for (const [garbled, correct] of Object.entries(CHINESE_FIXES)) {
            if (content.includes(garbled)) {
                content = content.replace(new RegExp(garbled, 'g'), correct);
                modified = true;
                console.log(`  Fixed: ${garbled} -> ${correct}`);
            }
        }
        
        // Write back the fixed content if any changes were made
        if (modified) {
            fs.writeFileSync(filePath, content, 'utf8');
            console.log(`  Saved changes to: ${filePath}`);
        } else {
            console.log(`  No changes needed for: ${filePath}`);
        }
    } catch (error) {
        console.error(`  Error processing ${filePath}: ${error.message}`);
    }
}

// Function to process all frontend-legacy HTML files
function processFrontendLegacyFiles() {
    const files = fs.readdirSync(FRONTEND_LEGACY_DIR);
    for (const file of files) {
        if (file.endsWith('.html')) {
            // Skip test files
            if (file === 'test-router.html') {
                continue;
            }
            const filePath = path.join(FRONTEND_LEGACY_DIR, file);
            fixFile(filePath);
        }
    }
}

// Main function
console.log('Starting to fix Chinese encoding issues in frontend-legacy HTML files...');
processFrontendLegacyFiles();
console.log('All frontend-legacy HTML files have been processed.');
